POST http://localhost:3333/videos
Content-Type: application/json

{
	"title": "videos node",
	"description": "Esse é o video 01",
	"duration": 180
}

###

GET  http://localhost:3333/videos

###

PUT  http://localhost:3333/videos/af2861c1-1c78-499b-8e9a-a5cba29e1b01
Content-Type: application/json

{
	"title": "videos 02",
	"description": "Esse é o video 02",
	"duration": 180
}

###
DELETE  http://localhost:3333/videos/85574ecb-5061-44d3-8224-bad21d31be3c